# Numpy Basic

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
#2d array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
#3d array
c=np.array([[[1,2,3,4],[5,6,7,8]]])
print(c)

[[[1 2 3 4]
  [5 6 7 8]]]


In [4]:
#dtype array
d=np.array([1,2,3,4],dtype=complex)
print(d)
d1=np.array([1,2,3,4],dtype=float)
print(d1)
d2=np.array([1,2,3,4],dtype=bool)
print(d2)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
[1. 2. 3. 4.]
[ True  True  True  True]


In [5]:
#arange
e=np.arange(1,5)
print(e)
e1=np.arange(1,5,2)
print(e1)

[1 2 3 4]
[1 3]


In [6]:
#reshape
f=np.array([[1,2,3,4],[5,6,7,8]])
print(f.reshape(4,2))


print(f.reshape(2,4))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
#zeros and ones
g=np.zeros((3,4))
print(g)
h=np.ones((3,4))
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
#random
# it will give you random number betwwen 0 to 1
i=np.random.random((3,4))
print(i)


[[0.49768154 0.41965835 0.1503625  0.88759177]
 [0.34254028 0.39176654 0.13775618 0.05826081]
 [0.55226377 0.22299167 0.55589014 0.34741031]]


In [9]:
#linspace
j=np.linspace(1,5,10)
print(j)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [10]:
#identity
k=np.eye(3)
print(k)

k1=np.identity(5)
print(k1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Array Attributes

In [11]:
l1=np.arange(10)
l2=np.arange(12,dtype=float).reshape(3,4)
l3=np.arange(8).reshape(2,2,2)
print(l1)
print(l2)
print(l3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
#ndim
print(l1.ndim)
print(l2.ndim)
print(l3.ndim)

1
2
3


In [13]:
#shape
print(l1.shape)
print(l2.shape)
print(l3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [14]:
#size
# The size attribute of a NumPy array returns the total number of elements in the array.
print("Size of l1:", l1.size)
print("Size of l2:", l2.size)
print("Size of l3:", l3.size)

Size of l1: 10
Size of l2: 12
Size of l3: 8


In [15]:
#itemsize
# The itemsize attribute of a NumPy array returns the size of each element in the array in bytes.
print("Itemsize of l1:", l1.itemsize)
print("Itemsize of l2:", l2.itemsize)

Itemsize of l1: 8
Itemsize of l2: 8


In [16]:
#dtype
print(l1.dtype)
print(l2.dtype)
print(l3.dtype)

int64
float64
int64


# Changing Datatypes


In [17]:
#astype
l1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# Array Operation

In [18]:
arr1=np.arange(12).reshape(3,4)
arr2=np.arange(12,24).reshape(3,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
#arithmetic  *  /  % + -
#relarional  == < >   !=
print(arr1*8)
print(arr2>9)

[[ 0  8 16 24]
 [32 40 48 56]
 [64 72 80 88]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [21]:
#vector operation
#arithmetic

arr1+arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [22]:
arr1*arr2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [23]:
#max ,min ,prod,sum
print(arr1)
np.max(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(11)

In [24]:
#axix wise min or max
print(np.max(arr1,axis=1))
np.sum(arr1,axis=1)

[ 3  7 11]


array([ 6, 22, 38])

In [25]:
#mean /median /standard /variance
np.mean(arr1)
np.median(arr2)

np.float64(17.5)

In [26]:
#trigo function
np.tanh(arr1)


array([[0.        , 0.76159416, 0.96402758, 0.99505475],
       [0.9993293 , 0.9999092 , 0.99998771, 0.99999834],
       [0.99999977, 0.99999997, 1.        , 1.        ]])

In [27]:
#dot produt
arr3=arr2=np.arange(13,25).reshape(4,3)
arr3

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [28]:
np.dot(arr1,arr3)

array([[120, 126, 132],
       [400, 422, 444],
       [680, 718, 756]])

In [29]:
#log and exp
np.log(arr1)

/tmp/ipython-input-29-196050986.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

# Indexing Slicing

In [30]:
m1=np.arange(10)
m2=np.arange(12).reshape(3,4)
m3=np.arange(8).reshape(2,2,2)

m3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
#1D
print(m1[-1])

9


In [32]:
#2d array
print(m2)
m2[2,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(11)

In [33]:
m3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
m3[1,0,1]

np.int64(5)

In [35]:
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
m2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [37]:
m2[0:3:2,0:4:3]

array([[ 0,  3],
       [ 8, 11]])

In [38]:
m2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [39]:
m2[1,::3]

array([4, 7])

In [40]:
m4=np.arange(27).reshape(3,3,3)

m4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
m4[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [42]:
m4[1,1:,1:]

array([[13, 14],
       [16, 17]])

In [43]:
m4[0,1,::]

array([3, 4, 5])

# Iterating

In [44]:
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
m4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
for i in m1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [48]:
for i in np.nditer(m4):
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [49]:
#reshape

In [50]:
#transpose
np.transpose(m2)
#or
m2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [51]:
#ravel  changing 2 or 3d array into 1D array
m2.ravel()
m4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [60]:
#horizontal stacking
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a3=np.arange(24,36).reshape(3,4)

print(a1)
print(a2)
np.hstack((a1,a2))
np.hstack((a1,a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3, 12, 13, 14, 15, 24, 25, 26, 27],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 28, 29, 30, 31],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 32, 33, 34, 35]])

In [61]:
#vertical Stacking

np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [62]:
#horzontal
np.hsplit(a1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [63]:
#vertical
np.vsplit(a1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]