#np.sort
Return a sorted copy of an array.

In [4]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[96, 29, 36, 85],
       [49, 20,  2, 22],
       [15, 48, 56, 22],
       [21, 92, 46, 22],
       [85, 85,  2, 31],
       [16, 80, 85, 57]])

In [8]:
np.sort(a)[::-1]

array([99, 92, 90, 84, 83, 75, 64, 60, 39, 38, 28, 24, 20, 19, 14])

In [10]:
np.sort(b,axis=0)

array([[15, 20,  2, 22],
       [16, 29,  2, 22],
       [21, 48, 36, 22],
       [49, 80, 46, 31],
       [85, 85, 56, 57],
       [96, 92, 85, 85]])

# np.append
The numpy.append() appends values along the mentioned axis at the end of the array
https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
# code
np.append(a,200)

array([ 38,  28,  20,  99,  60,  19,  24,  92,  83,  39,  14,  75,  64,
        90,  84, 200])

In [15]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[96., 29., 36., 85.,  1.],
       [49., 20.,  2., 22.,  1.],
       [15., 48., 56., 22.,  1.],
       [21., 92., 46., 22.,  1.],
       [85., 85.,  2., 31.,  1.],
       [16., 80., 85., 57.,  1.]])

# np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [16]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.


In [19]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f=np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [20]:
np.unique(e)


array([1, 2, 3, 4, 5, 6])

In [21]:
np.unique(f)

array([1, 2, 3])

# np.expand_dims
   With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [23]:
np.shape(a)

(15,)

In [25]:
np.expand_dims(a,axis=1)

array([[38],
       [28],
       [20],
       [99],
       [60],
       [19],
       [24],
       [92],
       [83],
       [39],
       [14],
       [75],
       [64],
       [90],
       [84]])

# np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [26]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [27]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 3,  4,  7,  8, 11, 12, 13, 14]),)

In [34]:
#np.where(condition,return value if condition is true ,return if condition is false
np.where(a%2==0,0,a)

array([ 0,  0,  0, 99,  0, 19,  0,  0, 83, 39,  0, 75,  0,  0,  0])

# np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [36]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [37]:
np.argmax(a)

np.int64(3)

In [44]:
b

array([[96, 29, 36, 85],
       [49, 20,  2, 22],
       [15, 48, 56, 22],
       [21, 92, 46, 22],
       [85, 85,  2, 31],
       [16, 80, 85, 57]])

In [39]:
np.argmax(b,axis=1)

array([0, 0, 2, 1, 0, 2])

In [38]:
np.argmax(b,axis=0)

array([0, 3, 5, 0])

# np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [41]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [40]:
np.cumsum(a)

array([ 38,  66,  86, 185, 245, 264, 288, 380, 463, 502, 516, 591, 655,
       745, 829])

In [43]:
b

array([[96, 29, 36, 85],
       [49, 20,  2, 22],
       [15, 48, 56, 22],
       [21, 92, 46, 22],
       [85, 85,  2, 31],
       [16, 80, 85, 57]])

In [42]:
np.cumsum(b,axis=1)

array([[ 96, 125, 161, 246],
       [ 49,  69,  71,  93],
       [ 15,  63, 119, 141],
       [ 21, 113, 159, 181],
       [ 85, 170, 172, 203],
       [ 16,  96, 181, 238]])

# np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [46]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [51]:
np.percentile(a,80)

np.float64(85.2)

# np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [52]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [53]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 3, 2, 0, 0, 2, 1, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef
Return Pearson product-moment correlation coefficients.

In [57]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [58]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [59]:
items=[10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False,  True, False,  True, False, False, False, False,
       False, False, False, False,  True, False])

In [60]:
a[np.isin(a,items)]

array([20, 60, 90])

# np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [61]:
a


array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [62]:
np.flip(a)

array([84, 90, 64, 75, 14, 39, 83, 92, 24, 19, 60, 99, 20, 28, 38])

In [63]:
b

array([[96, 29, 36, 85],
       [49, 20,  2, 22],
       [15, 48, 56, 22],
       [21, 92, 46, 22],
       [85, 85,  2, 31],
       [16, 80, 85, 57]])

In [66]:
np.flip(b,axis=1)

array([[85, 36, 29, 96],
       [22,  2, 20, 49],
       [22, 56, 48, 15],
       [22, 46, 92, 21],
       [31,  2, 85, 85],
       [57, 85, 80, 16]])

# np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [67]:
# code
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [68]:
np.put(a,[0,1],[38,28])

In [69]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

# np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [70]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [71]:
np.delete(a,[0,2,4])

array([28, 99, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

# Set functions

    np.union1d
    np.intersect1d
    np.setdiff1d
    np.setxor1d
    np.in1d


In [72]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
np.intersect1d(m,n)

array([3, 4, 5])

In [74]:
np.setdiff1d(n,m)

array([6, 7])

In [75]:
np.setdiff1d(m,n)

array([1, 2])

In [77]:
np.in1d(m,1)

/tmp/ipython-input-3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

# np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

In [78]:
a

array([38, 28, 20, 99, 60, 19, 24, 92, 83, 39, 14, 75, 64, 90, 84])

In [79]:
np.clip(a,a_min=25,a_max=75)

array([38, 28, 25, 75, 60, 25, 25, 75, 75, 39, 25, 75, 64, 75, 75])